server:
  port: 8080
spring:
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/water?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    cache: false
