server:
  port: 8080
spring:
  main:
    allow-circular-references: true
  mvc:
    date-format: "yyyy-MM-dd"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://39.107.104.16:3306/water?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    cache: false
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: cn.edu.ldu.watercloud.entity
